# Generated by Django 5.0 on 2023-12-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotroommessage',
            name='answer_number',
            field=models.IntegerField(default=0),
        ),
    ]
